### ISSUE TITLE
muliple instances of clock 

### ISSUE THREAD

**Issue by ashah976** [thooyork/thooClock#18]
If I call multiple times then it launches multiple instances, but I only want once instance of the clock running

` $('#myclock').thooClock({})`

I then try to call `$('#myclock').remove()` before calling the above but it doesnt show the clock 
Is there a way to deal with this please?

**Comment by thooyork** [comment]
If I get you right you want to display multiple instances of the clock, but you only want one clock actually ticking ? Unfortunately thats not possible. As soon as you register the instance the clock is running. Why would you need that feature ?

**Comment by thooyork** [comment]
Wont fix
