### ISSUE TITLE
the clock looks fuzzy (unclear) when I run the page using localhost

### ISSUE THREAD

**Issue by slom44** [thooyork/thooClock#21]
when I open the file index.html directly (double click), I see clear pretty clock
![image](https://user-images.githubusercontent.com/16323043/144184101-262f2f22-f971-438e-866c-61cb3981ad68.png)

but if I run the page using localhost, this is what I get:
![image](https://user-images.githubusercontent.com/16323043/144184168-6e53c6b9-83aa-4120-8e08-cab6df8a8f67.png)

same file, same code , same location
what's wrong ?

**Comment by thooyork** [comment]
I never had this issue. Looks like the client resizes the canvas with a fixed size. Is it same behaviour in all browsers ?
