### ISSUE TITLE
License

### ISSUE THREAD

**Issue by soif** [thooyork/thooClock#4]
Hi again

I read the MIT license included in your source code, but as I'm not an expert in this field, would please just tell me if I could include your javascript file in phpMydomo, which is itself a free opensource HomeAutomation software.
http://www.phpmydomo.org/

Cheers

**Comment by thooyork** [comment]
Hi,

I appreceate your interest in my clock plugin. Feel free to use it in your project, a link or mention would be nice ;-)
I noticed your latest pull requests and appreceate your bugfixes.

This was a project from late 2012 just to teach myself how to write 
jQuery plugins and get my hands on drawing with the canvas element …

The thing is at the moment I do not have time to wrap my head around this code again and
 fix further issues (such as remove alarm hand etc.) 
If you find a solution feel free to modify the code.

Thx for your interest 

Cheers

Tom

**Comment by soif** [comment]
Thank you for your reply

I will certainly include your clock in my project. And I perfectly understand your time issue : _we all are in the same boat ;-)_

BTW thank you for the FF text fix ;-)

cheers
