### ISSUE TITLE
Digits are very small on FireFox

### ISSUE THREAD

**Issue by soif** [thooyork/thooClock#5]
The hours numbers on Firefox (mac, 35.0.1) are **really small** , ie:

![firefox](https://cloud.githubusercontent.com/assets/101618/6998362/6f26ec12-dbe0-11e4-8fce-9cd5fb8a85db.png)

While looking beautifull on Safari :

![safari](https://cloud.githubusercontent.com/assets/101618/6998365/86227580-dbe0-11e4-88ab-3ecb5e56a670.png)

_Captures done with your vanilla install on both browsers._

tchusss

**Comment by thooyork** [comment]
fixed this.
